// Generated by https://quicktype.io

export interface PokemonDataData {
  
    id:              number;
    name:            string;
    pokemon_species: PokemonBasic[];

}

export interface PokemonBasic {
    name: string;
    url:  string;
}


